// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuhkleijqspawibaqver.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1aGtsZWlqcXNwYXdpYmFxdmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDAzNDMsImV4cCI6MjA2NTExNjM0M30.zTXM3Dm8tD1n1tiC5Rg4DrC51jLCmDhjlRfAKcDIldA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);